version: "3.9"
services:
  backend:
    build: ./api
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build: ./crypto-dashboard
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
